### PR TITLE
Automate CLI and HTTP API doc generation

### PR DESCRIPTION
**Pull request by petar**
1. move http-api-docs tool here
2. regenerate API docs on new go-ipfs tags

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by petar** [comment]
@lidel auto-generation of API docs is ready for a review. Should anyone in particular be tagged on the auto-generated PL request?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by lidel — APPROVED** [review]
LGTM, tweaked PR template to add `needs/triage` and `P0` latels – should be enough to prioritize review without hardcoding specific people.

Preview of PR created by this workflow can be seen in https://github.com/ipfs/ipfs-docs/pull/884 (https://github.com/ipfs/ipfs-docs/pull/884/commits/8c977f7061f4aea97a9503b58c70522f72d72351 specifically)

I switched CI trigger to schedule/cron, so this is ready to be merged.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by johnnymatthews — APPROVED** [review]

**Pull request merged**
