### PR TITLE
Adds IPNI page in Concepts

### PR DESCRIPTION
**Pull request by ElPaisano**
Addresses https://github.com/ipfs/ipfs-docs/issues/1296

### CODE REVIEW

**Comment by ElPaisano** [comment]
https://github.com/TorfinnOlsen I'm trying to add you as a reviewer for this but GH won't let me...

**Comment by ElPaisano** [comment]
> I'm trying to add you as a reviewer for this but GH won't let me https://github.com/TorfinnOlsen

@BigLep I can't add https://github.com/TorfinnOlsen to this PR for review. Wondering if this is a permissions issue i.e maybe Torfinn needs to be added to github-mgmt?

**Comment by TorfinnOlsen** [comment]
I am unable to edit the PR due to permissions, but am leaving this note here to amplify that I am rewriting sections of this document presently to more accurately reflect some of the characteristics of the service!  cc: @ElPaisano

**Comment by BigLep** [comment]
@TorfinnOlsen @ElPaisano : yes, permissions can be added via https://github.com/ipfs/github-mgmt

**Comment by TorfinnOlsen** [comment]
@ElPaisano FYI I'm about halfway done with a local copy I've cached it's needed a healthy bit of rewriting. I should finish the entire rewrite by EoW(need feedback from my team). I'll submit the request to get edit access to GithubMgmt so we can submit this as a PR and request feedback on my rewrite from our other contributors.

**Comment by ElPaisano** [comment]
Redraft from @TorfinnOlsen is here https://github.com/TorfinnOlsen/IPNIdocumentation/blob/main/IPFSdocsIPNI.md. Will edit this and add to the PR

**Comment by ElPaisano** [comment]
@TorfinnOlsen made a number of edits to your redraft, mostly writing and styling things

The preview is here https://bafybeiar2gvxko64iy2u22ckiur25ixzb2akzctxyr3sxa5ggvgpi7sw6m.on.fleek.co/concepts/ipni/

Can you read through this and let me know if everything looks on from a technical standpoint?

**Comment by TorfinnOlsen** [comment]
Sorry @ElPaisano just realized I had an unsent message to you in Slack. The edit looks great happy to proceed on our end! Thank you for all the work on this.

**Review by DONALDSULLENDER — APPROVED** [review]

**Review by johnnymatthews — APPROVED** [review]

**Pull request merged**
