### PR TITLE
Changes to RPC API doc generation to ignore `NoRemote: true` 

### PR DESCRIPTION
**Pull request by TMoMoreau**
# Describe your changes

Change to one line, based on instructions from @hacdias in this comment: https://github.com/ipfs/ipfs-docs/issues/1397#issuecomment-1386861881

I'm not 100% certain that I did this correctly.

# Files changed

- \ipfs-docs\tools/http-api-docs\endpoints.go

# What issue(s) does this address?

- Addresses issue #1397 

# Does this update depend on any other PRs?

No

## Checklist before requesting a review
- [x] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [ ] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

### CODE REVIEW

**Comment by ElPaisano** [comment]
checked out this branch locally and I was also seeing that `/api/v0/key/export` is still listed in the Kubo RPC API doc. 

I tried a few things, in addition to the suggestion https://github.com/ipfs/ipfs-docs/issues/1397#issuecomment-1386861881:
- Seeing what would happen if I set the variable `ignore` in `Endpoints` to be true when `name == "/api/v0/key/export"`:
  `ignore := cmd.Run == nil || IgnoreEndpoints[name] || name == "/api/v0/key/export"`
- Seeing what would happen if I set IgnoreEndpoints
  ```
  var IgnoreEndpoints = map[string]bool{
    "/api/v0/key/export" : true,
  }
  ```
  
  In both cases, didn't fix the issue, but also I'm not super familiar with Go :D
  
   @hacdias any other thoughts on this? Also, are the RPC API pages being autogenerated by scraping info from these pages https://github.com/ipfs/kubo/tree/master/core/commands?

**Comment by ElPaisano** [comment]
@TMoMoreau on a related note, is this the only instance that we are aware of where an RPC command is being autogenerated when it shouldn't be? Or are there other incorrect endpoints in the RPC API doc?

**Comment by hacdias** [comment]
@TMoMoreau the PR is working as intended. However, the CI only updates the docs at a scheduled job once a day if there is a new Kubo version. That is, the Kubo RPC docs are not regenerated at each commit. At least, that is my understanding from the actions you can find under the `.github` directory at the root of the repository. 

I pushed [d03cd36](https://github.com/ipfs/ipfs-docs/pull/1423/commits/d03cd3607c49312d8e6b3aca97df889e19bdf336) to update the README documentation in the generation tool to include the new file path for the RPC docs. To run the tool, you should navigate to `tools/http-api-docs` and run:

```
go run ./http-api-docs/main.go > ../../docs/reference/kubo/rpc.md
```

@ElPaisano I noticed you updated the way the links work in #1348. Unfortunately, if you execute the command above, those nice links will be reverted to the wrong links we used to have before. I pushed [fe969ac](https://github.com/ipfs/ipfs-docs/pull/1423/commits/fe969ac33533c61c139f0499339ba5ab0f02e708) to fix those links of the RPC API at the root, that is, in the generator tool.

---

I run the tool and pushed [d2be7fb](https://github.com/ipfs/ipfs-docs/pull/1423/commits/d2be7fb008b89a725e1d105781bbcec69912759f) with the new Kubo RPC docs. You will see that at least 8 endpoints were removed since they have the `NoRemote` option set to `true`. Here's the preview: https://bafybeidrje25kxpmb5c6kym7g2cjqsgdfkpq7cuzijbxeqf4wpdc6yt7du.on.fleek.co/

**Review by hacdias — APPROVED** [review]

**Comment by hacdias** [comment]
@TMoMoreau @ElPaisano I merged it as it was working as intended. Let me know if you have any further questions!

**Comment by ElPaisano** [comment]
@hacdias thanks for the help and the explanation

**Pull request merged**
