### PR TITLE
Adds plausible analytics to IPFS docs.

### PR DESCRIPTION
**Pull request by johnnymatthews**

### CODE REVIEW

**Review by TMoMoreau — APPROVED** [review]
👍

**Comment by lidel** [comment]
@johnnymatthews @TMoMoreau any context behind adding this I could catch up on? (issue/notion/channel?)
Is there a longer plan to replace Countly across our stack and websites, or is Plausible limited to docs websites?

**Comment by TMoMoreau** [comment]
@lidel As far as I know, Plausible is limited to the Docs. I can't speak to the reason why Plausible is being used, that's a question for Johnny or Jenni.

@johnnymatthews is OoO for the next 2 weeks, @jennijuju is OoO for the day.

**Comment by jennijuju** [comment]
@lidel you can see more details about the plausible deployment [here](https://www.notion.so/pl-strflt/Docs-Analytics-8ed29e7fd33e44b9b4a55c4bdff39d25). You can see why we chose plausible [here](https://www.notion.so/pl-strflt/Docs-Analytics-8ed29e7fd33e44b9b4a55c4bdff39d25#c8b4bd4f0447460d9ad2eee323100d48).

We'd like to test plausible out for at least one quarter and see if it provides the analytical metrics we need for improving our docs, before sunsetting the existing service like countly and GA. If you have any concerns about this proposed solution, feel free to leave a comment in the above notion page.

Currently, we dont have an active plan to deploy it to ipfs-related sites other than https://docs.ipfs.tech. Tho one of the pros of plausible is it's super easy to deploy, we have documented the process[ here](https://www.notion.so/pl-strflt/Add-analytics-to-a-site-a60d51f8ba6a4de78e42178e34124e86).

**Comment by 2color** [comment]
Some additional nice things about Plausible:
- Open source and can be self hosted
- Analytics can be made public 

> Is there a longer plan to replace Countly across our stack and websites, or is Plausible limited to docs websites?

I was actually going to suggest that for the IPFS website and blog.

**Comment by lidel** [comment]
Thanks!  I agree, it is worth testing it for a while. We will decide what to do with Countly after a quarter or two.

ps. @2color if you want, feel free to run a similar experiment on non-docs IPFS websites, including discourse forums (https://plausible.io/docs/discourse-integration).  I suspect high % of people reading docs is technical enough to run adblocker which also kills plausible metrics when loaded via `plausible.io` domain. Unsure if we want to set up a proxy on `plausible.ipfs.tech` (https://plausible.io/docs/proxy/introduction) or just live with it.

**Comment by SgtPooki** [comment]
> @lidel you can see more details about the plausible deployment [here](https://www.notion.so/pl-strflt/Docs-Analytics-8ed29e7fd33e44b9b4a55c4bdff39d25). You can see why we chose plausible [here](https://www.notion.so/pl-strflt/Docs-Analytics-8ed29e7fd33e44b9b4a55c4bdff39d25#c8b4bd4f0447460d9ad2eee323100d48).
> 
> We'd like to test plausible out for at least one quarter and see if it provides the analytical metrics we need for improving our docs, before sunsetting the existing service like countly and GA. If you have any concerns about this proposed solution, feel free to leave a comment in the above notion page.
> 
> Currently, we dont have an active plan to deploy it to ipfs-related sites other than https://docs.ipfs.tech. Tho one of the pros of plausible is it's super easy to deploy, we have documented the process[ here](https://www.notion.so/pl-strflt/Add-analytics-to-a-site-a60d51f8ba6a4de78e42178e34124e86).

I've requested access to the linked notion pages. @jennijuju can you let me know when that's been granted?

**Pull request merged**
