### PR TITLE
feat: document deprecated RPC API commands

### PR DESCRIPTION
**Pull request by lidel**
Leverages Status field from https://github.com/ipfs/go-ipfs-cmds/pull/225 + https://github.com/ipfs/go-ipfs/pull/8802  and uses that information while generating HTTP RPC API reference docs.

- "Experimental" and "Deprecated" commands are listed in separate sections after regular ones
- Each command has additional warning box informing about deprecated/experimental state, in case someone opens its docs via direct link

## Demo

These additional annotations are not present in go-ipfs 0.12, but will be present when 0.13 ships.

For now, I generated `docs/reference/http/api.md` using this PR for easier preview:

- https://bafybeietbmpk2lj2vs23optcn4ar6ru4qj5wnr65dygzm5zukwspeay7c4.ipfs.cf-ipfs.com/reference/http/api/#deprecated-rpc-commands
- https://bafybeietbmpk2lj2vs23optcn4ar6ru4qj5wnr65dygzm5zukwspeay7c4.ipfs.cf-ipfs.com/reference/http/api/#experimental-rpc-commands

deprecated-2022-03-18_21-54

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
- Switched to go-ipfs-cmds v0.7.0 which includes https://github.com/ipfs/go-ipfs-cmds/issues/93
- Merged https://github.com/ipfs/go-ipfs/pull/8802  – we are now waiting for go-ipfs 0.13 to ship, then we can switch this PR to 0.13.0 and re-generate `docs/reference/http/api.md`  before merging.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
I rebased this to build docs for already released go-ipfs 0.12.2, this way we can merge it without waiting for 0.13.

**Pull request merged**
