### PR TITLE
Update ipfs-updater.md

### PR DESCRIPTION
**Pull request by mrodriguez3313**
Upgrading version numbers to latest ipfs-update tool version 1.8.0

https://discord.com/channels/806902334369824788/847893063841349652/968664117160341514

With regards to the automation of the docs version number. Maybe there can be a variable in a config file that holds the version number of the tool. With my experience with Jekyll sites, (idk what this one is) but there would be a variable that could look like this `ipfs-update-tool : 1.8.0` and in each location where the version number goes (ex: line 20, etc...) we instead put `{{ site.ipfs-update-tool }}`. Now instead of manually changing each version number in this doc you just change the config file.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Nice thanks! We should probably write a script to do this for us at some point...

**Comment by johnnymatthews** [comment]
>  With my experience with Jekyll sites

Nah, this is a VuePress site. But works in a similar way.

The only problem with having variables like that built into the markdown, is that it makes the markdown itself harder to read. It's also less portable. It'd be better to have a script with a list of files it needs to look at, and then scans those files periodically to check whether they're showing the latest `ipfs-update` version.

Anyway, thanks for this PR. It's in draft mode right now though, are you still working on it?

**Comment by mrodriguez3313** [comment]
The reason I had it as a draft was to see if the conversation of automating it would develop. And if it would be something that I could help take care of? It could be its own seperate PR anyways and I could change this to done.

**Review by johnnymatthews — APPROVED** [review]

**Comment by johnnymatthews** [comment]
Yeah it's best if we created a new issue and PR to address this automation problem.

There's an issue here for discussion: https://github.com/ipfs/ipfs-docs/issues/1128

**Pull request merged**
