### PR TITLE
Pubsub multibase encoding

### PR DESCRIPTION
**Pull request by TMoMoreau**
Documenting and clarifying the requirement of multibase encoding when publishing data to a pubsub topic.

### CODE REVIEW

**Comment by TheDiscordian** [comment]
LGTM, I personally really like that you linked to a tool to assist devs in converting their topic string to Base64URL (really handy especially if someone is coming to the docs after wondering why their `pub` isn't working). It is linked to an external tool, not 100% sure how kosher that is, but I'm sure @johnnymatthews could bless us with his opinion/wisdom 🙏.

Tagging @Annamarie2019 hoping this more complete PR will help alleviate some confusion ❤️.

**Review by lidel — CHANGES_REQUESTED** [review]
This is great, but this markdown file is generated, so these changes will get overridden when a new release of go-ipfs ships :( 

You need to update https://github.com/ipfs/ipfs-docs/tree/main/tools/http-api-docs generator and special-case this specific endpoint.

FYSA I filled https://github.com/ipfs/go-ipfs-cmds/issues/224  to add a programatic way to indicate which string fields are expected to be multibase – if someone is able to implement that, then generating docs should be way easier, but it is also fine to special-case in `tools/http-api-docs` for now, if you find it easier.

**Comment by TheDiscordian** [comment]
@lidel thank you so much putting us on the correct path here (even with options)!

**Comment by TheDiscordian** [comment]
Closed PR as per Lidel's message.

**Pull request closed without merging**
