### PR TITLE
Update use-existing-private-key.md

### PR DESCRIPTION
**Pull request by chiro-hiro**
# Describe your changes
Update the JS example to match new interface of `option`

# Files changed

-  docs/how-to/use-existing-private-key.md

# What issue(s) does this address?

N/A 

# Does this update depend on any other PRs?

No

## Checklist before requesting a review
- [x] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [x] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

### CODE REVIEW

**Comment by ElPaisano** [comment]
@2color I'm not familiar enough with this, can you take a look?

**Comment by ElPaisano** [comment]
Haven't heard anything back on this pull request. I'm closing for now, can reopen if I hear back.

**Comment by chiro-hiro** [comment]
@ElPaisano I think, @2color isn't response.  It isn't a good reason to close this.

**Comment by ElPaisano** [comment]
> @ElPaisano I think, @2color isn't response. It isn't a good reason to close this.

@chiro-hiro apologies for the confusion. I've reopened and asked @TheDiscordian to double check this PR, as 2color is unavailable at the moment

**Comment by TheDiscordian** [comment]
@achingbrain I wasn't able to figure this out via [CONFIG.md](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md). Where does this information live? Are you able to review this?

**Comment by AlexxNica** [comment]
> @achingbrain I wasn't able to figure this out via [CONFIG.md](https://github.com/ipfs/js-ipfs/blob/master/docs/CONFIG.md). Where does this information live? Are you able to review this?

@TheDiscordian I believe the reference for `options` now lives in https://github.com/ipfs/js-ipfs/blob/master/docs/MODULE.md#optionsinit

**Comment by ElPaisano** [comment]
Triaging old issues. 

Because js-ipfs is now in maintenance mode and has been superseded by [Helia](https://github.com/ipfs/helia/wiki), legacy js-ipfs docs are being removed from ipfs-docs. For js-ipfs specific info, please see [the js-ipfs repo docs](https://github.com/ipfs/js-ipfs/blob/master/docs/README.md). 

Additionally, we are trying to direct readers to implementation specific docs, such as [the docs in the Kubo repo](https://github.com/ipfs/kubo/tree/master/docs).

As such, the page referenced here has been removed, so this PR is no longer relevant.

**Pull request closed without merging**
