### PR TITLE
create stylesheet for alert-panels

### PR DESCRIPTION
**Pull request by slopey112**
Closes [#402](https://github.com/ipfs/docs/issues/402).

As a side note, I think it makes more sense if note panels becomes info panels. Seeing as the beta only uses tips and notes, I think the styling would look better if tips and and notes look different.

### CODE REVIEW

**Comment by ericronne** [comment]
fyi
https://github.com/ipfs/docs/issues/402

**Comment by jessicaschilling** [comment]
@cwaring -- can you please have a glance when you get a minute? Thanks.

**Comment by ericronne** [comment]
I didn't check the code here, but these were already designed btw …
image

**Comment by slopey112** [comment]
> I didn't check the code here, but these were already designed btw …
Yep, this pull request just puts those designs in a stylesheet.

**Comment by cwaring** [comment]
thanks @slopey112, I'll review this soon.

**Comment by jessicaschilling** [comment]
@cwaring -- just checking in? Thanks!

**Comment by johnnymatthews** [comment]
Wow, this has been around for a while! Looks fine to me, so I'm gonna merge this in.

**Pull request merged**
