### PR TITLE
Fixes https://github.com/ipfs/ipfs-docs/issues/1266 - delete duplicate Contribution page

### PR DESCRIPTION
**Pull request by ElPaisano**
1. Deletes https://docs.ipfs.tech/project/contribute/
2. Redirects links for deleted https://docs.ipfs.tech/project/contribute/ to http://localhost:8080/community/contribute/ways-to-contribute/

### CODE REVIEW

**Comment by johnnymatthews** [comment]
There's a build error stopping this PR from merging:

```
2022-09-14T18:49:38.263Z: [vuepress] No matching page found for sidebar item "/project/contribute"
```

Looks like you need to remove the respective sidebar item.

**Comment by ElPaisano** [comment]
@johnnymatthews thanks for the review.

I think that [fe34a24](https://github.com/ipfs/ipfs-docs/pull/1279/commits/fe34a24f337cb63c56d8027abb4518a791e9fc77) should address this.

**Review by TMoMoreau — APPROVED** [review]
Looks good to me. Seems to be building fine now.

**Comment by johnnymatthews** [comment]
> Is there a way to preview fleek errors locally so that I can avoid pushing a broken build in the future? I tested the site locally before pushing using npm start and manually checking for errors on the local copy of the site. The npm logs didn't show any build errors - @ElPaisano 

The errors that Fleek spits out are the same you should get when running `npm run start`. If it doesn't build locally, then it _shouldn't_ build in Fleek. It's the same the other way around (doesn't build in Fleek, then it _shouldn't_ build locally).

**Pull request merged**
