### PR TITLE
Fix the output of updated file

### PR DESCRIPTION
**Pull request by winksaville**
The self key output is "Hello again IPFS" after being updated so I've
changed the "Make a change to your file, .." to reflect that.

### CODE REVIEW

**Comment by winksaville** [comment]
One other minor issue with the initial CID, QmaMLRsvmDRCezZe2iebcKWtEzKNjBaQfwcu7mcpdm8eY2, for hello.txt with "Hello IPFS":
```
ipfs add hello.txt

> added QmaMLRsvmDRCezZe2iebcKWtEzKNjBaQfwcu7mcpdm8eY2 hello.txt
> 13 B / 13 B [===================================================================] 100.00%
```
On my computer I see QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG:
```
$ echo "Hello IPFS" > hello.txt
wink@rpi48:~/ipfs-exper/ipns-test
$ hexdump -C hello.txt
00000000  48 65 6c 6c 6f 20 49 50  46 53 0a                 |Hello IPFS.|
0000000b
wink@rpi48:~/ipfs-exper/ipns-test
$ ipfs add hello.txt
added QmUVTKsrYJpaxUT7dr9FpKq6AoKHhEM7eG1ZHGL56haKLG hello.txt
 11 B / 11 B [=====================================================] 100.00%
```
Also notice that the length is 13 Bytes in the documentation but 11 Bytes my Linux machine. If you'd like I can make that change too.

**Comment by johnnymatthews** [comment]
Nice catch! Looks like the copy & paste demon got me on this occasion.

> Also notice that the length is 13 Bytes in the documentation but 11 Bytes my Linux machine. If you'd like I can make that change too. - @winksaville 

Yeah if you wouldn't mind adding that update too, it'd be really appreciated!

**Comment by winksaville** [comment]
Forced push a new change, actually I had a copy/paste bug too, thus the second force push :)

**Comment by johnnymatthews** [comment]
Ah, everyone loves a git force-push 😄

I'm assuming this is ready for review now.

**Review by johnnymatthews — APPROVED** [review]
Look good from my end! Thanks for finding and jumping on this issue @winksaville!

**Comment by winksaville** [comment]
:), txs for the review!

**Pull request merged**
