### PR TITLE
Expand MFS section of "File systems and IPFS" page

### PR DESCRIPTION
**Pull request by realChainLife**
Closes issue [243](https://github.com/ipfs/ipfs-docs/issues/243)

Expanded the documentation by demonstrating how to use MFS, e.g. creating a directory, adding a file, removing a file and more. Also expanded the Unixfs section by:
- adding an example of a protobuf data format
- describing the importing and exporting functions
- adding additional resources.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
@realChainLife this is great! Thanks for submitting this! I'm gonna got through it and make some structural changes where necessary. I'll also grab a file-system expert to check we're not missing anything. This is an excellent first draft!

**Comment by realChainLife** [comment]
Awesome @johnnymatthews, thanks for the fixes.

**Comment by johnnymatthews** [comment]
This looks ready to merge into `master`! @realChainLife please email me ([email address is in my profile](https://github.com/johnnymatthews)) to get the bounty payment sorted.

**Comment by johnnymatthews** [comment]
Changed the branch to `release/staging` so we can get an IPFS preview (CircleCI doesn't build previews on branches made by non-org members.

**Comment by realChainLife** [comment]
This is great @johnnymatthews if there's anymore docs related bounties still unassigned, I can give them a go as well. The IPNS concept doc for example, otherwise emailing you shortly.

**Pull request merged**
