### PR TITLE
[wip] feat: enable pwa

### PR DESCRIPTION
**Pull request by cwaring**
+ base config for offline PWA functionality

### CODE REVIEW

**Comment by cwaring** [comment]
This needs further testing before merging as it appears that the addition of the service worker causes [this dom node issue](vuejs/vuepress/issues/1692) on reload.

**Comment by jessicaschilling** [comment]
@cwaring - what's the status of this?

**Comment by cwaring** [comment]
This is functional but I've not fully tested how it interacts with IPFS so I'm leaving in the icebox for the meantime.

**Comment by johnnymatthews** [comment]
This PR is nearly a year old so I'm gonna close it.

**Pull request closed without merging**
