### PR TITLE
feat: prox plausible traffic

### PR DESCRIPTION
**Pull request by 2color**
Based on https://github.com/ipfs/ipfs-blog/pull/467 which is already working.

This just adds the proxying functionality.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Review by lidel — CHANGES_REQUESTED** [review]
sgtm but we need set up `foo.ipfs.tech` for this, so there are no third-party names involved.

**Comment by Jorropo** [comment]
@lidel we can take a look at this again now that ipfs.tech is setup ?

**Comment by 2color** [comment]
@Jorropo Based on some tests we did, there's not much benefit to this unless we use the same origin. I can't remember the details, but delegating _only_ a subdomain to Cloudflare is not possible on a normal unless you pay a lot of $.

There may be better ways of doing this using Netlify Edge or Deno Deploy, assuming we can easily do subdomain delegating (which based on recent experiences is easier than Cloudflare)

**Comment by ElPaisano** [comment]
Hey @2color going through open PRs right now. 

Is this still relevant or can we close it out? If it's still relevant, does work still need to be done on this? LMK

**Comment by 2color** [comment]
There's not benefit to this with the current domain. It would need to be the same origin to bring benefit.

**Comment by ElPaisano** [comment]
Based on @2colors comment, closing this PR out

**Pull request closed without merging**
