### PR TITLE
IPFS for web developers

### PR DESCRIPTION
**Pull request by leon-do**

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Nice. I'm guessing this is a work-in-progress, so I'm gonna convert this PR to a draft.

**Comment by leon-do** [comment]
hey @johnnymatthews 

Can you take a look at it and see what I need to add/remove/edit?

**Comment by johnnymatthews** [comment]
In the `website-on-ipfs` branch, all the relevant tutorials are stored in `ipfs-docs-v2/docs/how-to/websites-on-ipfs/`. Let's keep that structure. All the tutorials you create in this series should live in `ipfs-docs-v2/docs/how-to/ipfs-for-web-developers`.

Also, a lot of what you've written is a duplicate of what already exists in the original [`website-on-ipfs` branch](https://github.com/ipfs/ipfs-docs-v2/tree/website-on-ipfs). The [Single Page Website guide](https://github.com/ipfs/ipfs-docs-v2/blob/website-on-ipfs/docs/how-to/websites-on-ipfs/single-page-website.md) is pretty much complete already. 

Cherry-pick what's already in the `website-on-ipfs` branch into your branch, then carry on from there.

**Comment by johnnymatthews** [comment]
Also, don't worry about individually hosting the images on IPFS and then referencing the CID in your markdown. The build process we use automatically hosts assets like images and stylesheets on IPFS, before replacing the relative links in the markdown with the CID of those assets. Check out host to host and store images in the [contribution guidelines](https://docs-beta.ipfs.io/community/contribute/grammar-formatting-and-style/#images).

**Comment by johnnymatthews** [comment]
Gonna close this PR after our talk @leon-do. Let make the next PR against `ipfs/ipfs-docs:feat/ipfs-for-webdevs`.

**Pull request closed without merging**
