### PR TITLE
fix: match documentation with ipfs desktop button label

### PR DESCRIPTION
**Pull request by davidlfox**
# Describe your changes
Just a language match between what's in IPFS desktop app and the documentation

# Files changed
- docs/how-to/websites-on-ipfs/single-page-website.md

# What issue(s) does this address?
- good documentation

# Does this update depend on any other PRs?
- not from what I can tell

## Checklist before requesting a review
- [✅ ] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [ ✅] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

### CODE REVIEW

**Comment by ELALEMAN007** [comment]
Enviado desde mi Samsung Mobile de Telcel
Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Review by 2color — APPROVED** [review]
Thanks!

**Comment by 2color** [comment]
There are two broken links on that page that need to be fixed so that the linter can pass:
FILE: docs/how-to/websites-on-ipfs/single-page-website.md
[✖] http://randomplanetfacts.xyz/ → Status: 403
[✖] https://gateway.pinata.cloud/ipfs/QmW7S5HRLkP4XtPNyT1vQSjP3eRdtZaVtF6FAPvUfduMjA → Status: 403

**Comment by davidlfox** [comment]
> There are two broken links on that page that need to be fixed so that the linter can pass: FILE: docs/how-to/websites-on-ipfs/single-page-website.md [✖] http://randomplanetfacts.xyz/ → Status: 403 [✖] https://gateway.pinata.cloud/ipfs/QmW7S5HRLkP4XtPNyT1vQSjP3eRdtZaVtF6FAPvUfduMjA → Status: 403

what happened to/who owns the domain/url? i acknowledge that it has an error, but pinning HTML files in Pinata requires a paid plan. im just submitting a PR for a typo. how should i update the doc? removing the section on the domain and everything referencing it seems counter to the page's purpose

**Comment by lidel** [comment]
@davidlfox these errors are not your fault, the problem is that CI automation runs tests against modified files, and if a file was not modified for a while, it is possible that some links no longer work, and the first time we detect that is here.

In this case, let's just remove links. The website does not need to exist for the tutorial to make sense.

**Pull request merged**
