### PR TITLE
Updated navigation for ipfs-docs

### PR DESCRIPTION
**Pull request by ElPaisano**
### Update 4 
- Addressed latest feedback 
- Updatedhttps://bafybeifqd2u5onupe7bmmckkojjckzadik7drmxiu35zvi6g7kcf6doa6e.on.fleek.co/
- Updates described, request for discussion on some of the changes https://github.com/ipfs/ipfs-docs/pull/1405#issuecomment-1397729008

### Update 3
- Addressed latest feedback
- Updated link here https://bafybeiceboemgqaotjdixw7tvxkjsibplbjvcty5e5wyy5lqiqw5icgna4.on.fleek.co/

### Update 2
- Addressed more feedback, latest version based off that is here https://bafybeiegcjowsakflddu3pnqrsgfg52afmyqo3saqwxwhgvdjrs5hnlkxi.on.fleek.co/
- Updates / discussion here https://github.com/ipfs/ipfs-docs/pull/1405#issuecomment-1387618094

### Update 1 
- Addressed @lidel @2color initial feedback https://github.com/ipfs/ipfs-docs/pull/1405#pullrequestreview-1250501738 and https://github.com/ipfs/ipfs-docs/pull/1405#issuecomment-1385305969, latest version based off of that is here https://bafybeicbmboodievzzqsfacqe5d4s7ishuo7krhagtr4wr2ww4e7ibutrm.on.fleek.co/
- [summary of updates](https://github.com/ipfs/ipfs-docs/pull/1405#issuecomment-1386211290)
- [discussion needed](https://github.com/ipfs/ipfs-docs/pull/1405#issuecomment-1386237814)

## Summary (edited based on updates)
This PR is the first major proposed update to improve the ipfs-docs experience. 

** Update 5 (latest) https://bafybeifqd2u5onupe7bmmckkojjckzadik7drmxiu35zvi6g7kcf6doa6e.on.fleek.co/**
**Update 4 (latest) https://bafybeifqd2u5onupe7bmmckkojjckzadik7drmxiu35zvi6g7kcf6doa6e.on.fleek.co/**
**Update 3 https://bafybeiceboemgqaotjdixw7tvxkjsibplbjvcty5e5wyy5lqiqw5icgna4.on.fleek.co/**
**Update 2  https://bafybeiegcjowsakflddu3pnqrsgfg52afmyqo3saqwxwhgvdjrs5hnlkxi.on.fleek.co/**
**Update 1 https://bafybeicbmboodievzzqsfacqe5d4s7ishuo7krhagtr4wr2ww4e7ibutrm.on.fleek.co/**
**Original version https://bafybeif2y2izlgaxx2bl42w3f4itjwvnojacrud5rynfagzjtpljuha6d4.on.fleek.co/**

It proposes:

1. A new layout / navigation for ipfs-docs. Changes `config.js` stuff https://github.com/ipfs/ipfs-docs/pull/1405/files#diff-52eb86351480925d61947a58caca1ea76d10950ec26533f16f37cb12a3519dff
   - The topbar is now the main navigation
   - Each topbar category has a custom menu of all the subcategories and items under that top level category
   - Some sidebar menus are now collapsable
   - Top bar categories are:
      - Get Started -> "Install" content + js-ipfs guide that was in "Basics" + a subset of the material from "Concepts"
      - Concepts 
      - Guides -> "How-tos"
      - Reference -> "API & CLI"
      - Project -> contains current Project material plus current Community stuff
      - Case Studies -> dropdown with case study pages
   - Gets rid of [Basics category](https://docs.ipfs.tech/basics/) and moves / redirects content
      - `/basics` redirects to `/install`
      - `/basics/desktop-app` redirects to `/how-to/desktop-app`
      - `/basics/go/command-line-quick-start` redirects to `/how-to/command-line-quick-start`
      - `/basics/js/js-ipfs` redirects to `/install/js-ipfs`
      - `/basics/ipfs-implementations` redirects to `/concepts/ipfs-implementations`
   - Get rid of "Case Studies" as top level navigation items and moves content to live as a subcategory under Concepts (this content is already in that folder, so redirects don't need to be applied)
1. Renaming some pages so that titles and categories are hopefully more sensible and intuitive
    - `/install/command-line` renamed from "Kubo on the command line" to "Kubo"
    - `/how-to/README` renamed from "How-tos" to "Guides"
    - `/install/server-infrastructure.md` renamed from "Server infrastructure with IPFS Cluster" to "IPFS Cluster"
    - `/project/README` renamed from "The IPFS project" to "Project"
    - `/reference/README.md`renamed from "API & CLI" to "Reference"
    - `/reference/go/api.md` renamed from "IPFS in Go" to "Advanced Kubo Usage"
    - `/install/README` renamed from "Install IPFS" to "Getting Started". Also renames headers in this page.
        - `## File storage` -> `## IPFS Desktop`
        - `## Application development` -> `## IPFS Kubo`
        - `## IPFS as infrastructure` -> `## IPFS Cluster`
        - `## Surf the decentralized web` -> `## IPFS Companion`
    -  `/how-to/command-line-quick-start` renamed from "Command-line quick start" to "Advanced Kubo Tutorial" (recall that `/how-to/command-line-quick-start` is a relocated / redirected copy of what is now `/basics/go/command-line-quick-start`)
    -  `/how-to/desktop-app` renamed from "Desktop app" to "Advanced IPFS Desktop Tutorial" (recall that `/how-to/desktop-app` is a relocated / redirected copy of what is now `/basics/desktop-app`)
    -   `/install/js-ipfs` renamed from "IPFS in JavaScript" to "js-ipfs" (recall that `/install/js-ipfs` is a relocated / redirected copy of what is now `/basics/js/js-ipfs`)
1. Adds custom css for navbar so that it text doesn't get messed up on a screen resize https://github.com/ipfs/ipfs-docs/pull/1405/files#diff-64d3e686e1f494fff70ff8aadbaafe1f7c7e7fdcbbbdf476a28321c6d0cb4f7d

### CODE REVIEW

**Comment by ElPaisano** [comment]
@2color I know you mentioned wanting to keep this at the top level. However, I do think that the less top level categories we have, the better - the whole point of this overhaul is to make the nav simpler, so I think it's better to have less top level options, and "Case Studies" as a category under "Concepts" makes enough sense to me (at least for the moment, until we make bigger changes to the site). If you or anyone else still fills strongly about this tho, lmk

**Comment by ElPaisano** [comment]
> Gets rid of [Basics category](https://docs.ipfs.tech/basics/) and moves / redirects content
>
> /basics redirects to /install
> /basics/desktop-app redirects to /how-to/desktop-app
> /basics/go/command-line-quick-start redirects to /how-to/command-line-quick-start
> /basics/js/js-ipfs redirects to /install/js-ipfs
> /basics/ipfs-implementations redirects to /concepts/ipfs-implementations

Same ideas as removing Case Studies as a top level nav item - the less top level categories we have, the better, since the whole point of this overhaul is to make navigation simpler. The content that is currently in "Basics" has other locations where it would make sense, so I think it makes sense to move content, remove as a top level category, and do redirects. 

If anyone has strong opinions about it, pls lmk

**Review by lidel — CHANGES_REQUESTED** [review]
@thank you @ElPaisano, love the top navbar, hige quality of life improvement.

I think the main feedback from me about quick improvement   is that "Get Started" should  tell you how to get started :upside_down_face: :smile: 

Currently, i tells you what is there to install, but you need to:
-  read wall of text to reason what to click (what is "IPFS Companion"? How it is different from "Kubo"?) 
-  realize you are missing basic "what is ipfs" explainer, and click to Concepts to see it
- be really motivated to find content if you are pragmatist you look for Case studies ("is anyone using this? i won't read further unless i feel it is not vaporware")

Perhaps we could improve the left menu in  "Getting Started" to be close  to something like:

> 2023-01-16-182414_277x627_scrot



- reading `Case Studies` remains as one of prominent ways to get started (cc @2color)
- `Learn More` will open `Concepts` with more info
  - I would also include [`Academic Papers`](https://docs.ipfs.tech/concepts/further-reading/academic-papers/) before  `Learn More`, but don't feel strongly about this one.
- `Install` is not only dry app names, but hint at use case
- `Install` also includes pointers to SDKs for people interested in solutions for specific languages (we don't need to maintain these, could be links to remote documentations).

**Comment by 2color** [comment]
The top nav bar is a much-needed addition! Thanks for figuring this out @ElPaisano.

---

To recap some of our sync discussions with @TMoMoreau:

- Move the top-level community page under the project. This is to make space for the new community page on the IPFS website.
- Make case studies a top-level menu item

--- 
**To build on @lidel's feedback** 

> I think the main feedback from me about quick improvement is that "Get Started" should tell you how to get started 🙃 😄

I agree! 

I think getting started should ease users into IPFS and guide them into getting something useful done. For many, just a high-level understanding is enough, for others, it's pinning a file using a pinning service and seeing it load on multiple gateways, and for some, it's installing IPFS.

Practically, we have a page with some buttons to the different sections/sub-pages of the getting started. 

Building on top of @lidel's [suggestion](https://user-images.githubusercontent.com/157609/212736043-084d5ca8-0ac6-4d67-98cd-f6163297ae18.png), I would add to **Learn Basics** and **Install**, a third **Pin Files** page/section which shows how to pin a file using Web3.storage.



> - we show subset of items from `Concepts` in  `Getting Started` as well, for easier discovery

👍

> - reading `Case Studies` remains as one of prominent ways to get started (cc @2color)

In the same vein, having the case studies as a top level. We _could_ also add a link here 

- `Learn More` will open `Concepts` with more info

👍. I'd note that in the long term, I envision the concepts we present in getting started being more concise.

  - I would also include [`Academic Papers`](https://docs.ipfs.tech/concepts/further-reading/academic-papers/) before  `Learn More`, but don't feel strongly about this one.

I feel that this doesn't belong in getting started. I would instead make it a second level (top level in the side bar) of the concepts page:

Screen Shot 2023-01-17 at 12 41 54 PM

> - `Install` is not only dry app names, but hint at use case

👍

> - `Install` also includes pointers to SDKs for people interested in solutions for specific languages (we don't need to maintain these, could be links to remote documentations).

👍

**Comment by ElPaisano** [comment]
Apologies for the delay  in updating here, wasted way too much troubleshooting a silly build issue...

## Summary of updates:
- _Added Case Studies as a top bar menu item._ Mirrors how we currently have Case Studies set up, in that there's no "main page" for case studies but just a menu category where each dropdown item is a link to a case study page. Note that, on the landing page (`\`) the sidebar is the same as the top bar (but the sidebar changes on other pages as we've already discussed) https://bafybeicbmboodievzzqsfacqe5d4s7ishuo7krhagtr4wr2ww4e7ibutrm.on.fleek.co/
- Moved "Community" content under "Project" https://bafybeicbmboodievzzqsfacqe5d4s7ishuo7krhagtr4wr2ww4e7ibutrm.on.fleek.co/project/
- Came up with submenus "Quickstarts" and "Basic Concepts" under top level "Get Started" to address @lidel https://github.com/ipfs/ipfs-docs/pull/1405#pullrequestreview-1250501738 + @2color comments about what should be contained in "Get Started". Further discussion here. 
- Broke "Academic Papers" out of "Further Reading" per @2color https://github.com/ipfs/ipfs-docs/pull/1405. It should be noted that, since the "Further Reading" category only contained one page "Academic Papers", moving "Academic Papers" out to the top of the "Concepts" menu means that "Further Reading" is empty (so I deleted it) https://bafybeicbmboodievzzqsfacqe5d4s7ishuo7krhagtr4wr2ww4e7ibutrm.on.fleek.co/concepts/further-reading/academic-papers/

**Comment by ElPaisano** [comment]
## Discussion requested

RE update: _Came up with submenus "Quickstarts" and "Basic Concepts" under top level "Get Started" to address @lidel https://github.com/ipfs/ipfs-docs/pull/1405#pullrequestreview-1250501738 + @2color comments about what should be contained in "Get Started"_

@lidel @2color I like the idea of showing a subset of basic concepts stuff in "Getting Started". Seems like we have a few different opinions. So,

### Menu subcategory names?
For the menu sub categories, I chose the names "Quickstarts" (for the basic install guides for tools, SDKs, implementations, etc.) and "Basic Concepts" (for the category with the subset of items from concepts). @lidel "Install" would also make sense to me but I'm not sure about "Learn basics". @2color any thoughts?

### What subset of concepts should we include under "Get Started"?
@lidel @2color I agree that "Hashing", "Immutability", "Persistence", "Content addressing and CIDs" and a link to further concepts titled "More Concepts" makes sense in this section. However, I do think that "Academic Papers" should stay in the main concepts section. Also @lidel your comment 
> Install also includes pointers to SDKs for people interested in solutions for specific languages (we don't need to maintain these, could be links to remote documentations).
makes sense. I added a link to Iroh's install guide, but I think that, just to keep this in scope, we should keep the other menu items as is, at least for this PR. We can add more / update it in a future PR

### Adding a pin files page / section to "Get Started"?
@2color RE your comment 
> Building on top of @lidel's [suggestion](https://user-images.githubusercontent.com/157609/212736043-084d5ca8-0ac6-4d67-98cd-f6163297ae18.png), I would add to Learn Basics and Install, a third Pin Files page/section which shows how to pin a file using Web3.storage. (since this is a new page, it's out of scope for this PR)

I agree this is out of scope, but I think it's a good idea. Im thinking of creating issues to organize all of this docs overhaul work, so I can create an issue for that idea and then we can figure out how to slot it into upcoming work

**Comment by ElPaisano** [comment]
Alright another update. @lidel addressed most of your points I think 

## Summary of Update 2

In the "Get Started" category
- Makes sidebar menus expand by default for visibility
- "Basic Concepts" is above "Quickstarts"
- "Quickstarts" now contains the following, which matches @lidels requested content with slightly different names and ordering. Note that "Helia SDK for JavaScript" is not in here because I'm not aware of there being docs for Helia yet (recently asked achingbrain) 
image

- Moves what is currently https://docs.ipfs.tech/install/ipfs-updater/ into "Guidies" -> "Customize Your Install" since it seems like this is a guide with more specific content that shouldn't live in "Get Started" anyways. Plus, it wasn't in lidels requested list of menu items.
  - Adds related redirect `/install/ipfs-updater/ /how-to/ipfs-updater/`
- As you can see from the above screenshot, what is currently https://docs.ipfs.tech/how-to/run-ipfs-inside-docker/ now lives under "Get Started" -> "Quickstarts" per lidels requested menu layout
  - Adds related redirect `/how-to/run-ipfs-inside-docker/ /install/run-ipfs-inside-docker/`

**Comment by mishmosh** [comment]
Eventually, **Quickstarts** should not link to individual implementations, but tutorials/setup instructions for how to solve specific problems with IPFS. For example, Share public data, Create a private network, Build a p2p mobile app, etc.

That said, this is a nice move to a more scalable navigation and I'm in favor of moving forward.

**Comment by ElPaisano** [comment]
@mishmosh thanks for taking a look. RE "Quickstarts should not link to individual implementations, but tutorials/setup instructions for how to solve specific problems with IPFS. For example, Share public data, Create a private network, Build a p2p mobile app, etc." this is a good idea. I've started creating "parent"-level issues for us to track larger groups of work in as we continue with this reorg. One issue I created was https://github.com/ipfs/ipfs-docs/issues/1422 which includes your comment. The ideas is that we can all discuss further, create sub-issues for more scoped tasks, and then do the work 

@2color created https://github.com/ipfs/ipfs-docs/issues/1421 for your Pin files page/section suggestion and grouped it under the "parent"-level issue https://github.com/ipfs/ipfs-docs/issues/1422 since it seems like it falls into that category

**Comment by 2color** [comment]
- I would leave the menu header (that is current **Quickstarts**) as Install as they're all installation guides.
- I would –in a separate PR– create a separate and new Quick start menu item. This could be the home for the pin guide and other higher level problem-solving guides (which may use the installation guides as a prerequisite). This is also in line which @mishmosh's suggestion.
- SDK is not a good name in my opinion, because you're installing a node, not really an SDK.
- In the mid-term, I think having a one-page explainer, "Brief intro to IPFS" would be ideal for the Get Started section instead of essentially duplicating the existing links from Concepts. 

> Makes sidebar menus expand by default for visibility
 
This is great! 

> Moves what is currently https://docs.ipfs.tech/install/ipfs-updater/ into "Guides" -> "Customize Your Install" since it seems like this is a guide with more specific content that shouldn't live in "Get Started" anyway

Also great

**Comment by TMoMoreau** [comment]
- Get started > Install
  - Should we drop the "IPFS" from "IPFS Kubo for Go"?
  - I'm not sure if this is how Kubo should be referred to, or if it should just be "Kubo for Go".
  - Same question for "IPFS Kubo in Docker" and "IPFS Iroh for Rust".

- Agree with @2color about the word "advanced", as mentioned in the comment above, a different word may be better. I'm not sure what word would be better, but the IPFS Desktop guide in there was originally listed under the "Basics" section, because it is just the basics of IPFS Desktop.

- Still don't see the glossary anywhere in any of the navigation lists. I believe during the call this morning it was agreed the glossary should be included as an item under the "Reference" tab.
  - The glossary can still be accessed by clicking one of the direct links to it (from the landing page, for example), but even while on the glossary page, it still can't be found anywhere in the sidebar.

- One last thing I've been thinking about: It's weird to me that clicking on any of the items listed under `Get Started > Basic Concepts` takes you out of the `Get Started` section, and drops you in the `Concepts` section. I understand the items listed under the `Basic Concepts` section just link to their respective page in the `Concepts` section, but from the user standpoint, I click on the `Get Started` section, I click on the first link under `Basic Concepts`, and then I need to navigate  back to `Get Started` in order to continue on with reading the next basic concept.
  - If possible, it would be great to have the sidebar navigation stay the same after clicking on one of the `Basic Concepts` links, just like how the `Install` section works.

Overall, I believe this to be an improvement, there are just a few more things to work out.

**Comment by ElPaisano** [comment]
## Update 4

- Added glossary back into the "Concepts" (where it currently lives https://docs.ipfs.tech/concepts/glossary/), accidentally deleted it, good catch. See _The subcategories in "Content"_ for further discussion
- removed "Advanced Usage" subcategory in "Concepts". See _The subcategories in "Content"_ for further discussion

## Update 4 Discussion

A few points of discussion here based on latest reviews:

### The subcategories in Content

- Seems that there is a general consensus that we'd like to make a decent amount of changes to Concepts, including subcategories, sooner rather than later
- For this first effort, I'm proposing this layout for Concepts. It attempts to address a few points brought up in the latest reviews:
  - Agree w/ about the category Concepts > Advanced Usage and the word "advanced". That was an attempt to deal with having multiple, slightly different versions of the same guides i.e. how to install and use Kubo, how to install and use Desktop. Long story short, for the moment, I propose just breaking these "Advanced Usage" items out and renaming them. Long term, consolidate and continue to refine names / categories
- @Tmo RE location of the glossary: I added it back into Concepts. In the long term, it might make more sense elsewhere. ATM, I'm thinking of Reference as practical info on API, CLI, config, and general functionality for the various implentations, tools and things, whereas Concepts is theory and words and stuff. So, for the moment, because glossary is just conceptual definitions, I think it should live in Concepts for now
- @Tmo glad you called out the menu weirdness for Get Started > Basic Concepts. Long story short, tried a few things, but ran into the limits of vuepress. For example, tried explicitly setting an explicit menu for the pages in "Basic Concepts", but this messes up other things. What I came up with was this solution (at least for this first version), which I realize opens a larger can of worms:


   1. Reorganize 

## Update 4

- Added glossary back into the "Concepts" (where it currently lives https://docs.ipfs.tech/concepts/glossary/), accidentally deleted it, good catch. See _The subcategories in "Content"_ for further discussion
- removed "Advanced Usage" subcategory in "Concepts". See _The subcategories in "Content"_ for further discussion

## Update 4 Discussion

A few points of discussion here based on latest reviews:

### Guides > Advanced Usage

Agree w/ about the category Guides > Advanced Usage and the word "advanced". That was an attempt to deal with having multiple, slightly different versions of the same guides i.e. how to install and use Kubo, how to install and use Desktop. Long story short, for the moment, I propose just breaking these "Advanced Usage" items out into submenu headers and renaming them. Long term, consolidate, better categorize and  continue to refine names / categories

### The subcategories in Content

 I'm proposing this layout for Concepts. It attempts to address a few points brought up in the latest reviews:

- @Tmo RE location of the glossary: I added it back into Concepts. In the long term, it might make more sense elsewhere. ATM, I'm thinking of Reference as practical info on API, CLI, config, and general functionality for the various implementations, tools and things, whereas Concepts is theory and words and stuff. So, for the moment, because glossary is just conceptual definitions, I think it should live in Concepts for now
- @Tmo glad you called out the menu weirdness for Get Started > Basic Concepts. Long story short, tried a few things, but ran into the limits of vuepress + limits of our current folder structure. For example, tried explicitly setting an explicit menu for the pages in "Basic Concepts", but this messes up other things. Also, we could move some pages out of the concepts folder into the install folder, and the menu would make more sense, but then those pages would no longer be under concepts. So we are basically limited by how vuepress works

In the long term, it seems like the goal of cutting down on and pruning Concepts content will help solve alot of these problems. 

In the short term, so we can get this pushed ASAP and then continue iterate, I propose this:

1. Still include a header Get Started > Basic Concepts. 
2. Instead of Get Started > Basic Concepts opening a submenu with pages, it is now a link to `/concepts/what-is-ipfs`, first page in the Concepts > Basic Concepts submenu of the reorganized Concepts

**Comment by 2color** [comment]
> Instead of Get Started > Basic Concepts opening a submenu with pages, it is now a link to /concepts/what-is-ipfs, first page in the Concepts > Basic Concepts submenu of the reorganized Concepts

I think this is a good solution. 

> I'm proposing this layout for Concepts. It attempts to address a few points brought up in the latest reviews:

I like this structure

**Review by 2color — APPROVED** [review]

**Review by mishmosh — APPROVED** [review]

**Comment by ElPaisano** [comment]
@2color RE Things to fix
> The root community page is not reachable via the current menus


Good catch, made an update to the menu for https://bafybeigijsptnxqnfkle2h2jfkxjcos5w4p6stryahta5jmprrn3hped3a.on.fleek.co/project/ accordingly:
- In Project sidebar, there is now a "Community" header
- When you click that header, you see the community page https://bafybeigijsptnxqnfkle2h2jfkxjcos5w4p6stryahta5jmprrn3hped3a.on.fleek.co/community/ and a sidebar menu with the Community submenu items, plus the "Project" items below that
  
   image

- When you click on any of the "Project" sidebar items from "Community", the sidebar menu again displays the "community" header

> Now that have a proper case studies category, we can remove the case study from the file name (https://bafybeifqd2u5onupe7bmmckkojjckzadik7drmxiu35zvi6g7kcf6doa6e.on.fleek.co/case-studies/case-study-likecoin/ -> https://bafybeifqd2u5onupe7bmmckkojjckzadik7drmxiu35zvi6g7kcf6doa6e.on.fleek.co/case-studies/likecoin/)

Good call, renamed the case studies and added the redirects

**Comment by ElPaisano** [comment]
@lidel GH is showing that you're still requesting changes. LMK if there's anything else, but I think the updates addressed your feedback

**Comment by BigLep** [comment]
@ElPaisano : it looks like you're unblocked to get this merged in (except for CI checks).  Thanks for doing this.

**Pull request merged**
