### PR TITLE
host a git repo: change --bare to --mirror; rename (remove "style")

### PR DESCRIPTION
**Pull request by RubenKelevra**
- plus some minor language fixes

### CODE REVIEW

**Review by johnnymatthews — APPROVED** [review]

**Comment by johnnymatthews** [comment]
Ah. We need to change the sidebar nav too. Hang on.

**Review by johnnymatthews — CHANGES_REQUESTED** [review]
Since this your fork, I can't change the file directly. The issue here is that you've renamed the file, but not updated the sidebar to reflect the name change (this doesn't happen automatically unfortunately). To keep things simple, can you rename this file back to `host-git-style-repo.md`. You can keep the rest of the changes you've submitted, they all good :)

**Comment by BigLep** [comment]
@johnnymatthews : can you respond here so we can get this merged?

**Comment by johnnymatthews** [comment]
Sorry for the delay. This got buried in a mountain of GH notifications.

> For example the Linux repo inflates from around 8 GB to more than 50 GB this way.

Ah. In that case, yeah we really don't want users doing that.

> I think it's not worth it.

Agreed.

**Review by johnnymatthews — APPROVED** [review]
This looks good right now. Merge when ready.

**Comment by aschmahmann** [comment]
@johnnymatthews is this ready to merge, I see that CI is failing.

**Comment by johnnymatthews** [comment]
@RubenKelevra  you need to edit [line 195 in `/docs/.vuepress/config.js`](https://github.com/RubenKelevra/ipfs-docs-v2/blob/patch-1/docs/.vuepress/config.js#L195) to be:

```js
'/how-to/host-git-repo',
```

I can't edit your fork.

**Pull request merged**
