### PR TITLE
Update peering-with-content-providers.md

### PR DESCRIPTION
**Pull request by dome**
Add 8api.sh peers

### CODE REVIEW

**Review by DannyS03 — COMMENTED** [review]
thanks for the submission @dome. I can ping the first one but not the second

**Comment by dome** [comment]
> 
Screen Shot 2565-08-16 at 12 47 27

work fine from thailand

**Comment by johnnymatthews** [comment]
I also get responses from both peers:

```shell
$ › ipfs ping 12D3KooWGASC2jm3pmohEJXUhuStkxDitPgzvs4qMuFPaiD9x1BA                                                 ~
Looking up peer 12D3KooWGASC2jm3pmohEJXUhuStkxDitPgzvs4qMuFPaiD9x1BA
PING 12D3KooWGASC2jm3pmohEJXUhuStkxDitPgzvs4qMuFPaiD9x1BA.
Pong received: time=112.23 ms
Pong received: time=112.12 ms
Pong received: time=111.36 ms
Average latency: 111.90ms

$ › ipfs ping 12D3KooWRbWZN3GvLf9CHmozq4vnTzDD4EEoiqtRJxg5FV6Gfjmm                                                 ~
Looking up peer 12D3KooWRbWZN3GvLf9CHmozq4vnTzDD4EEoiqtRJxg5FV6Gfjmm
PING 12D3KooWRbWZN3GvLf9CHmozq4vnTzDD4EEoiqtRJxg5FV6Gfjmm.
Pong received: time=131.11 ms
Pong received: time=129.09 ms
Pong received: time=129.70 ms
Average latency: 129.97ms
```

**Comment by TMoMoreau** [comment]
8api.sh isn't known to us, are you affiliated with the IPFS team in any way?

**Review by BigLep — APPROVED** [review]
2022-08-26: agreed to merge because this isn't making things worse.  We do think this file should be rethought.

**Pull request merged**
