### PR TITLE
Add Crust into the IPFS case studies

### PR DESCRIPTION
**Pull request by yyd106**
As in the context of #487 , I created this PR to add Crust Network into the IPFS case studies.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@johnnymatthews -- now that you are guardian of the docs site, do you want to look over this? If you do include, we'll want to add more detail, quotes etc so it's consistent with the other case studies. Maybe @yyd106 can help facilitate that. 🙏

**Comment by yyd106** [comment]
> @johnnymatthews -- now that you are guardian of the docs site, do you want to look over this? If you do include, we'll want to add more detail, quotes etc so it's consistent with the other case studies. Maybe @yyd106 can help facilitate that. 🙏

Thanks for the review, I added some quotes accordingly. Please let me know if more detail is required.

**Comment by johnnymatthews** [comment]
Thanks for the write up @yyd106. It's an interesting read, however the case-studies section of IPFS docs is not a suitable place for this article.

> IPFS alone does not have a built-in mechanism to incentivize the storage of data for others. This is also an issue to be solved by Crust Network.

Filecoin is the incentivization layer _for_ IPFS.

Maybe I'm not understanding the purpose of Crust properly, but as it stands right now, we won't be merging this article. The case-studies section is a place for deep research into a particular product that leverages IPFS in an interesting way - it is not an advertisement space.

**Comment by jessicaschilling** [comment]
Given @johnnymatthews' comment above, I wonder if this piece (which does include a lot of useful info) would be better placed on one of Crust's own channels, like their Medium blog? If it's published off-site, we could link to it from the IPFS ecosystem directory (which is going live in the next week or two, and which includes an entry for Crust).

@yyd106 If you do end up facilitating that, let me know and I'll make sure the link to it gets added in the context of the ecosystem directory. Thanks!

**Comment by johnnymatthews** [comment]
Agreed. Just to reiterate, the article is an interesting read, and definitely contains some useful information.

**Comment by yyd106** [comment]
Thanks for the review. @johnnymatthews  I have deleted the part of "lack of built-in mechanism to incentivize the storage" part accordingly. 
@jessicaschilling Very appreciate your suggestion! We published this article in medium according to the feed back: https://medium.com/crustnetwork/crust-a-decentralized-storage-network-based-on-ipfs-85fbf247ac45

**Comment by jessicaschilling** [comment]
Thanks @yyd106 - we'll make sure this gets added as a link when the ecosystem directory goes live later this month.

**Comment by yyd106** [comment]
> Thanks @yyd106 - we'll make sure this gets added as a link when the ecosystem directory goes live later this month.

Hi @jessicaschilling , is there any link to the 'ecosystem directory'?

**Comment by jessicaschilling** [comment]
@yyd106 launch date is still TBD but keep an eye on ecosystem.ipfs.io for when it does appear.

**Comment by yyd106** [comment]
> @yyd106 launch date is still TBD but keep an eye on ecosystem.ipfs.io for when it does appear.

Got it, thanks a lot! @jessicaschilling

**Pull request closed without merging**
