### PR TITLE
WCAG AA

### PR DESCRIPTION
**Pull request by denim2x**
Changes for #293 were made according to `ipfs-css` styles.
Is another import necessary?

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Please post a comment in #293 requesting assignment to the issue. That way we don't duplicate effort.

**Comment by johnnymatthews** [comment]
@denim2x, thanks for submitting this PR. But doesn't address [the tasks specified in the issue](https://github.com/ipfs/ipfs-docs/issues/293#issuecomment-708870870). If you're still interested in completing the bounty, take a look at the tasks and either edit this PR, or create a new one. I'm gonna convert this PR to a draft since it still needs work.

**Comment by denim2x** [comment]
The need to "import IPFS-CSS" is mentioned, but how should I go about actually doing this? Since the styles are in Stylus, how exactly am I supposed to make use of CSS here?

**Comment by johnnymatthews** [comment]
Sorry for the delay in getting to this one @denim2x. 

Looking back, I was pretty vague when putting a bounty on #293. This PR addresses the main point of that issue, which is great. What I was looking for (although I didn't explicitly state it in the issue, my bad) was to make everything within IPFS-CSS available within the IPFS docs site, and make sure everything is styled against IPFS-CSS. But, it looks like that can be a task for another day.

This PR is correct, and addresses the issue of _"Fixing the color contrast for test links"_. One last thing that we need though is to run everything through https://webaim.org/resources/contrastchecker/ to make sure your changes address the issue. Once that's done and the results are posted here, I'll mark this PR as complete and merge things in.

**Comment by johnnymatthews** [comment]
Closing stale PR. Feel free to re-open.

**Pull request closed without merging**
