### PR TITLE
SEO fixes

### PR DESCRIPTION
**Pull request by 2color**
### What's in this PR
- Fixes links to the forum from `.io` to `.tech`
- Adds the cid keyword to the title for the content addressing page
- Improves the headers for the content addressing page to be more readable and SEO friendly
- Rename the Server Infrastructure page to IPFS cluster

### Background 
I was baffled to discover we're not the first result for `ipfs cid` on Google, only to discover we don't have the keyword in the title

Screen Shot 2022-08-18 at 11 19 54 AM

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by mishmosh — COMMENTED** [review]
I am not sure I agree with renaming server infrastructure to IPFS Cluster. Calling it "server infra" or something descriptive is more likely to catch the attention of users who don't know that Cluster is the solution to their problem. I believe this has been an issue historically. Can you git blame to find who made that change initially and discuss with them?

Everything else looks great, thank you. Your cleanups are a good reminder (for me and hopefully others too) that when deleting or renaming anything, we should also search the full repo for references to that thing and clean up accordingly.

How about forking the "server infrastructure" change into a separate PR and merging everything else?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by 2color** [comment]
> I am not sure I agree with renaming server infrastructure to IPFS Cluster. Calling it "server infra" or something descriptive is more likely to catch the attention of users who don't know that Cluster is the solution to their problem. I believe this has been an issue historically. Can you git blame to find who made that change initially and discuss with them?


Sounds good. I've reverted the change for now

It looks like it was server infrastructure from the get-go https://github.com/ipfs/ipfs-docs/commit/91e5026447e7e4109acf5fbf0566d1fac8a86858#diff-1c3779e94655b66d9a2ec90eb95bfcf977a0e04ccc41fc9e2974594e6b5a7d32

**Review by mishmosh — APPROVED** [review]

**Pull request merged**
