### PR TITLE
refactor: rename `go-ipfs` to `kubo`

### PR DESCRIPTION
**Pull request by johnnymatthews**
In preparation for Go-IPFS' big remove to _Kubo_, this PR changes `go-ipfs` to `kubo` and `Go-IPFS` to `Kubo.

## TODO / logistics

This PR depends on:

- [x] rename https://github.com/ipfs/go-ipfs → https://github.com/ipfs/kubo
- [x] release kubo 0.14 (final stable release)
- [x] update go.mod in this PR
- [x] manually run doc dgenerators for RPC API And CLI  and commit changes

<del> This PR should  merged before kubo 0.14 release is tagged at https://github.com/ipfs/kubo/releases – that way we will  see if automation responsible for generating RPC and CLI reference was migrated correctly</del> No, too many dependencies on having real release (and kubo has none), we need 0.14 first.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
Thank you, we will merge this AFTER kubo 0.14 is released :+1:

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> ipfs-docs@2.0.0 docs:build
> vuepress build docs

wait Extracting site metadata...
tip Apply local theme at /home/runner/work/ipfs-docs/ipfs-docs/docs/.vuepress/theme...
tip Apply theme local (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin vuepress-plugin-speedcurve ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
tip Apply plugin clean-urls (i.e. "vuepress-plugin-clean-urls") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
tip Apply plugin canonical (i.e. "vuepress-plugin-canonical") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin robots (i.e. "vuepress-plugin-robots") ...
tip Apply plugin @vuepress/html-redirect (i.e. "@vuepress/plugin-html-redirect") ...
tip Apply plugin chunkload-redirect (i.e. "vuepress-plugin-chunkload-redirect") ...
tip Apply plugin ipfs (i.e. "vuepress-plugin-ipfs") ...
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
[success] [webpackbar] Server: Compiled successfully in 18.36s
[success] [webpackbar] Client: Compiled successfully in 28.43s
wait Rendering static HTML...
17.server-bundle.js:35
if (window.location.hash.startsWith('#api-v0')) {
^

ReferenceError: window is not defined
    at Object.362 (17.server-bundle.js:35:1)
    at __webpack_require__ (server-bundle.js:27:30)
    at Module.361 (17.server-bundle.js:9:329)
    at __webpack_require__ (server-bundle.js:27:30)
    at Module.557 (17.server-bundle.js:66:90)
    at __webpack_require__ (server-bundle.js:27:30)
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
@johnnymatthews @BigLep @aschmahmann  @2color  (FYI)

I've pushed a pretty extensive refactor of https://docs.ipfs.io/reference/ page that clearly separates Kubo APIs (RPC, CLI) from generic one (HTTP Gateway). 

> 


This refactor covers all edge cases I was aware of, includes updating existing docs generators for both CLI and RPC, and updating references to clearly differentiate between HTTP API (which we want to mean HTTP Gateway) and implementation-specific  RPC over HTTP (which is `/api/v0` specific to Kubo)

- old `/reference/cli/` is now  `/reference/kubo/cli/`
- old `/reference/http/api/` is now  `/reference/kubo/rpc/`
-  new  `/reference/http/api/`  is an intermediate landing which has links to  `/reference/http/gateway/` and `/reference/kubo/rpc/` – most users won't see it, but we need it for backward-compatibility, so if someone uses old URL we can signal that RPC is not everything.
   - I've added some magic to ensure pages linking to `/reference/http/api/#api-v0-foo`  will get redirected to  `/reference/kubo/rpc/#api-v0-foo` – this way we don't have any UX regression around RPC docs

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
This is blocked until we have kubo `0.14.0`

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by Jorropo** [comment]
I've pushed the todos, I folowed the README.md but I'm not sure I was correct, could someone review pls ?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
Thank you @Jorropo! I replaced e18258e with 593dbc5  (docs got moved around, but after we merge this, it will be automated for the next release)

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Review by lidel — APPROVED** [review]

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

**Comment by lidel** [comment]
Merging – I will refine HTTP Gateway page in follow-up PR and ping folks for review (this PR is too big for humans).

**Pull request merged**
