### PR TITLE
remove dead link

### PR DESCRIPTION
**Pull request by TMoMoreau**
# Describe your changes

Just removing a dead link, in reference to issue #1381, specifically, @2color's comment on that issue.

# Files changed

- \docs\concepts\case-study-snapshot.md

# What issue(s) does this address?

- Issue #1381 

# Does this update depend on any other PRs?

No

## Checklist before requesting a review
- [ ] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [ ] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> ipfs-docs@2.0.0 docs:build
> NODE_OPTIONS=--openssl-legacy-provider vuepress build docs

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> ipfs-docs@2.0.0 docs:build
> NODE_OPTIONS=--openssl-legacy-provider vuepress build docs

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build failed...

```

> ipfs-docs@2.0.0 docs:build
> NODE_OPTIONS=--openssl-legacy-provider vuepress build docs

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Review by ElPaisano — CHANGES_REQUESTED** [review]
Unless I'm reading this wrong, looks like you're two commits behind main, so you don't have the updates that remove filecorgi. If that's the case, can you update this branch so that you have latest?

**Review by ElPaisano — COMMENTED** [review]
LGTM

**Review by ElPaisano — APPROVED** [review]

**Pull request merged**
