### PR TITLE
feat: add task completion survey banner

### PR DESCRIPTION
**Pull request by zebateira**
The banner shows in _all_ pages.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Review by jessicaschilling — APPROVED** [review]

**Comment by johnnymatthews** [comment]
Is this ready to be merged in?

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
@johnnymatthews waiting on the final url of the survey. @atopal will review and approve.

**Comment by johnnymatthews** [comment]
This PR is now pretty stale. Closing.

**Pull request closed without merging**
