### PR TITLE
Add descriptions of ipfs impls

### PR DESCRIPTION
**Pull request by Jorropo**

### CODE REVIEW

**Comment by Jorropo** [comment]
If people are unhappy about their description, just open a PR, this is meant to get people angry and want to fix it. :slightly_smiling_face:

**Comment by Jorropo** [comment]
please don't squash

**Review by johnnymatthews — APPROVED** [review]
Looks fine to me. I hate the fact that some projects refuse to capitalize the first letter of their name, but apart from that I'm cool with this PR.

**Comment by Jorropo** [comment]
> I hate the fact that some projects refuse to capitalize the first letter of their name

HAHAHA 🤣 
I have the other problems where some people write mine without it. 😄

**Pull request merged**
