### PR TITLE
export CLUSTER_HOST variable

### PR DESCRIPTION
**Pull request by mburns**
Not sure this works, still need to test

This is meant to trigger pinning the new website content to the Collab Cluster, which will fix the issues we've been having.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Can I merge this in @mburns, or are you still testing things?

**Comment by mburns** [comment]
talked this over at the Bifrost standup this morning, and settled on a different solution (https://github.com/protocol/bifrost-infra/pull/725). 

@johnnymatthews you can resume your regularly scheduled merge/deploys. Changes to the site should not cause errors anymore.

**Comment by cwaring** [comment]
@mburns should we push to cluster for the new protocol.ai config too?

**Comment by mburns** [comment]
@cwaring I believe so. Want to test that this works as expected first.

**Comment by mburns** [comment]
I don't have Circle permissions to test this further, but it appears to be what we need.

**Pull request merged**
