### PR TITLE
Add Audius case study and supporting scaffolding

### PR DESCRIPTION
**Pull request by jessicaschilling**
## In brief
**Adds Audius case study to the docs and sets up all the supporting scaffolding, specifically:**
- New page at `docs/concepts/case-study-audius.md`
- Adds new "Examples & Case Studies" nav section in `config.js` with new page; also moves "Usage ideas & examples" page into this section
- Edits TOC-style text in `docs/concepts/README.md` to account for new nav section
- Updates `layout-center.styl` for styles for float-right logo image and "big number boxes"; wanted to include these as real CSS rather than inline, since there will be a series of these case studies

## Reviews required
This PR needs approval from the following folks before merging ([preview page is here](https://bafybeiaondk7bcsldeiamntmqjtpsafho366blwad73zwfookp2woied5e.ipfs.dweb.link/concepts/case-study-audius/))
- @johnnymatthews, since docs is his site
- @autonome, for consistency
- @dmanjunath, since he's quoted
- @hareeshnagaraj, since he's quoted
- @roneilr, for overall accuracy

## Etc

Big thanks to @GraceRachmany for producing this case study!

Closes https://github.com/ipfs/ipfs-docs/issues/313.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@hareeshnagaraj and @dmanjunath -- I can't assign you as reviewers, but if you're able to note in a comment that we're OK to go live, that would be great. Thanks!

**Comment by cwaring** [comment]
I'll update this to migrate the custom styles into a component, that's the best way to make the style is reusable and ensure it's easy to maintain.

**Comment by jessicaschilling** [comment]
@autonome -- good call on both of those. The search on docs is better enough these days to help a lot without the need for overt tagging, but once we have more case studies, we can explore ways to categorize them.

@dmanjunath, @hareeshnagaraj, and/or @roneilr:
Dietrich raised a good question -- are there any materials we could link to in this case study that talk about how Audius uses HLS over IPFS? Would be great to give folks who are curious somewhere to learn more.

**Comment by jessicaschilling** [comment]
Updates received via email from the Audius team and staged here for final review:
https://bafybeihbrf5lmbfg7ueh5udhh4b2dn2krlmmariadsxmeemtgrng2vwbxa.ipfs.dweb.link/concepts/case-study-audius/

**Comment by jessicaschilling** [comment]
For the record: Approved by the Audius folks via email. Good to go. 😊

**Pull request merged**
