### PR TITLE
Ci cd test/vale testing branch do not merge

### PR DESCRIPTION
**Pull request by ElPaisano**
@TMoMoreau feel free to make all the changes you want to this branch. 

Just don't merge this, we will delete it once we confirm that the vale GH action is actually working as expected.

Steps:
1. [install vale on your local machine](https://vale.sh/docs/vale-cli/installation/).
Confirm the installation with vale --version. Output should be something like vale version 2.20.1.
2. Clone my fork
3. Every time you are running tests on this fork, you need to rebase off of https://github.com/ElPaisano/ipfs-docs/tree/ci-cd-test/vale so that you have the latest version of the linter code i.e. in case I've made changes to that branch. This applies any changes from the vale branch to this testing branch. To do this:
    a. `git checkout ci-cd-test/vale`
    b. `git rebase ci-cd-test/vale-testing-do-not-merge`
4. Switch into this branch. You can run a `git log -3` in this branch and compare it to `git log -3` in the `ci-cd-test/vale` to confirm that the rebase worked.
5. Run `vale sync` to sync the styles and packages so that your local config matches the GH action config. You only need to do this the first time
6. Make some edits to an MD file `<file-edited>.md`
7. Run vale <file-edited>.md. If any rules defined in write-good are violated / you violated the accept and reject files, output appears.
8. For testing purposes, you can either a) fix the violations and push your changes to GH or b) leave the violations there.
9. Commit and push to this branch
10. If you chose 7a, once you push, the vale GH action will run the same rules against your PR, and will pass. If you chose 7b, the GH action will fail and report errors.

Try and make one type of change per commit i.e. if you want to test the Oxford comma rule, only make changes to the markdown that involve comma stuff.

Ping me if you have questions

### CODE REVIEW

**Comment by ElPaisano** [comment]
Note: all issues with a severity level of `ERROR` will cause the action to fail. This is expected behavior and intentionally configured this way.

**Comment by TMoMoreau** [comment]
Ran vale locally on the `what-is-ipfs.md` file, removed all of the "errors" it returned, ran vale locally again, 0 errors returned. Committed the 0 error version back to this PR, vale still failing. Unsure if this is also expected behaviour, as vale is only flagging warnings in the file.

**Comment by ElPaisano** [comment]
@TMoMoreau glad you ran these tests, not sure what's happening here.
Tried removing all warnings in [0da562b](https://github.com/ipfs/ipfs-docs/pull/1340/commits/0da562bea46b485bd7d20cba7e478c54ea61b3fd) because I thought that might counted as a failure. That didn't work. So I tried remove the fail_on_error: true variable in the .yml file in [9c5d957](https://github.com/ipfs/ipfs-docs/pull/1340/commits/9c5d95720209d92f6cf26b290399fd07a6193e9b), but it's still failing :( 

I'll do some more investigation tomorrow. Thanks for the assistance!

**Comment by ElPaisano** [comment]
I thiiiiiiiink I have a fix! We need to run some more tests to be sure, but I'll at least explain the changes I made:

0. I noticed that, even though the commit was only showing vale issue annotations related to that commit, the vale GH action log was showing that vale was actually checking every single file in the repo. This is relevant to the fix. 
1. I also noticed that the runs were showing this error:
```
Error: reviewdog: Too many results (annotations) in diff.
  You may miss some annotations due to GitHub limitation for annotation created by logging command.
  Please check GitHub Actions log console to see all results.
```
From this error, it looks like GH Actions has a limit on the number of annotations that a GH action can make on a PR on a given run. So, my theory is that Vale was outputting more annotations than the limit allowed, which was causing it to fail regardless of whether or not there were issues of severity level `ERROR` even with `fail_on_error: false` and/or `vale_flags: "--no-exit"` (which just stops vale from returning any exit code, even in the case of an `ERROR`). Based off of this theory, after some mucking around...
2) I introduced a step that first [gets the file diff](https://github.com/ipfs/ipfs-docs/pull/1340/files#diff-9a6040a70edfc67842002b939c5d70625507e67cb7458001ca1f7cf956cb5c63R14-R18) and then tells vale to[ only check the file diff](https://github.com/ipfs/ipfs-docs/pull/1340/files#diff-9a6040a70edfc67842002b939c5d70625507e67cb7458001ca1f7cf956cb5c63R24). This relates to the first point, that Vale was checking everything, which plays into my theory that the vale check was violating the GH action annotation limit, so we needed to stay within that limit.
3) Then, I removed the `--no-exit` flag and reset `fail_on_error` to `true`. Why? Because the action should still fail if an `ERROR` is found i.e. a spelling error, a banned word, whatever we deem to be an `ERROR`
4) Lastly, I told the vale GH action to [only report an `ERROR`](https://github.com/ipfs/ipfs-docs/pull/1340/files#diff-9a6040a70edfc67842002b939c5d70625507e67cb7458001ca1f7cf956cb5c63R26), and disregard `WARNING` and `SUGGESTION`. This relates to the theory, so like the file diff step, the idea was to keep the annotations within the gh action limit.

Test:
1. [Intro one spelling error](https://github.com/ipfs/ipfs-docs/pull/1340/commits/4d8373c913c241abd35a86b2984ef2e2a2346d02) into a file that I know has no other issues of level `ERROR`. 

_Expected result:_ the action fails, the logs show that it failed because of this error, and that it did not fail for any other reason.
_Actual result:_ action fails, the logs show that it failed because of this error, and that it did not fail for any other reason.
2. [Remove the spelling error from step 1]([813d6e3](https://github.com/ipfs/ipfs-docs/pull/1340/commits/813d6e3998e75acbd1fbf2e64a236f4c358406a6)) 

_Expected result:_ the action succeeds, the logs show that no issues of level `ERROR` were found.
_Actual result:_ the action succeeds, the logs show that no issues of level `ERROR` were found.

**Comment by ElPaisano** [comment]
Once we have this is prod, the idea would be that the GH action should only have to look for `ERROR` issues anyways, because contributors should have already used Vale locally at that point to fix any other issues. So, the workflow would be:
1. Make edits
2. Use Vale locally to ideally fix all issues before pushing. Local vale will report all severity levels.
3. Commit and push
4. In case a contributor missed anything glaring (spelling, swear words lol, etc.), the action will catch that and fail, so that they at least have to fix that before we allow a merge

**Pull request closed without merging**
