### PR TITLE
Call out that the CLI and HTTP APIs are functionally the same.

### LINKED ISSUE #296: Call out that the CLI and HTTP APIs are functionally the same.
## [This issue has a bounty of $100](https://github.com/ipfs/devgrants/projects/1)

This is an issue to track curation and inclusion of https://github.com/ipfs/specs/blob/bc6a32ecff76d4b6e5a19955138305598b1a65eb/overviews/implement-api-bindings.md

That doc contains useful information on how the API works and how it relates to the CLI.

### PR DESCRIPTION
**Pull request by ChaituVR**
Closes #296 

Hello, So there is already a section in Http suggesting CLI is the same:

image

So added the same section to CLI (with minor changes):
image

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Excellent! Thanks for that @ChaituVR.

**Comment by ChaituVR** [comment]
@johnnymatthews Added that

**Comment by ChaituVR** [comment]
@johnnymatthews Added changes by running the script .. (which have some changes - maybe cli.md is not updated in a while with ipfs) Please review and let me know if i'm missing something :)

**Comment by johnnymatthews** [comment]
Sorry for the delay in getting to this PR. This looks good to me. Thanks for the assist!

**Pull request merged**
