### PR TITLE
`rust-ipfs` is no longer being maintained.

### PR DESCRIPTION
**Pull request by TMoMoreau**
# Describe your changes

rust-ipfs is no longer being maintained. Updated the list of implementations to include a note to reflect this. I did not remove the item in the table or the link to the archived repo.

~There is likely to be more mentions of `rust-ipfs` elsewhere, I'll crawl the docs to find them and add them to this PR.~

Exhaustive manual crawling of every page of the docs shows there are no other mentions of `rust-ipfs` (except for what is being addressed in PR #1446)

- [x] Find other mentions of `rust-ipfs`
- [x] Add a note to them that `rust-ipfs` is no longer maintained (possibly remove entirely)

# Files changed
 
- docs/concepts/ipfs-implementatios.md 

# What issue(s) does this address?

- #1447 

# Does this update depend on any other PRs?

- 

## Checklist before requesting a review
- [x] Passing the beta version of the **Check Markdown links for modified files** check. Action results can be viewed [here](https://github.com/ipfs/ipfs-docs/actions/workflows/action.yml).

## Checklist before merging
- [x] Passing all required checks (The beta **Check Markdown links for modified files** check is not required)

### CODE REVIEW

**Comment by TMoMoreau** [comment]
@ElPaisano Do you think this **bold** note that `rust-ipfs` is no longer being maintained is enough?

**Comment by TMoMoreau** [comment]
Ah, I just remembered this issue exists: #1360 

Getting that issue done should take priority over this one, and would also render this PR pointless.

**Comment by ElPaisano** [comment]
> Ah, I just remembered this issue exists: #1360
> 
> Getting that issue done should take priority over this one, and would also render this PR pointless.

Ahhhh ok I see that. I do like the reorg proposal better than just deleting them

However, out https://docs.ipfs.tech/basics/ipfs-implementations/, it would still make sense to remove other mentions of rust-ipfs

**Comment by TMoMoreau** [comment]
We can go ahead and get this merged, just need a quick approval. As mentioned in the original comment, there are no other mentions of `rust-ipfs` in the docs, (other than what was addressed in #1456, which has been merged.)

**Comment by TMoMoreau** [comment]
Oh, right, this PR is now redundant because of #1456, closing.

**Pull request closed without merging**
