### PR TITLE
[wip] Legacy site post-deprecation changes.

### PR DESCRIPTION
**Pull request by johnnymatthews**
**Don't merge yet.**

This PR contains a bunch of changes that should only be merged once this repo becomes the _main_ IPFS docs repo.

~Closes ipfs/docs #507 ipfs/docs #505 ipfs/docs #510~

### CODE REVIEW

**Comment by cwaring** [comment]
Please don't make one big PR for these changes. I'm working on the individual code features and it becomes really hard to test/review and collaborate correctly if everything is one branch moving. If you work on something in here that becomes a blocker then it holds up all the work from being deployed.

We should create small PRs as usual but merge those into a release branch that can be deployed separately.

**Comment by johnnymatthews** [comment]
Ah sorry, didn't realize it made things harder to deal with. I'll strip these out and make individual PRs.

**Comment by johnnymatthews** [comment]
I'll name all the deprecation-related branches `dep/foobar`. Should make things easier to deal with.

**Comment by cwaring** [comment]
I've [assigned myself](https://github.com/ipfs/docs/milestone/5) to the things I'll take care of, including most of the app config. If you can prep the content changes then we shouldn't hit any major merge conflicts.

**Comment by johnnymatthews** [comment]
Sounds good.

**Pull request closed without merging**
