### PR TITLE
Added EOSC and ExPaNds.eu entries

### PR DESCRIPTION
**Pull request by twdragon**
Added presentations made for European Open Science Cloud Symposium, describing IPFS as a prospective solution for decentralized data sharing and provenance.

# Files changed
- docs/concepts/further-reading/academic-papers.md

### CODE REVIEW

**Comment by ElPaisano** [comment]
Hi @twdragon thank you for submitting this PR. 

Two of the links you added are being flagged by the  GH action link checker. I manually tested the links to confirm that they are not working. could you please update this PR with the correct links? Thank you.

See below for more info:

```
=========================> MARKDOWN LINK CHECK <=========================

FILE: docs/concepts/further-reading/academic-papers.md
[✖] https://elettra.eu/ → Status: 0 Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/request/request.js:848:19)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[✖] https://pan-data.eu/sites/pan-data.eu/files/PaNdataODI-D6.1.pdf → Status: 0 Error: connect ECONNREFUSED 130.246.[39](https://github.com/ipfs/ipfs-docs/actions/runs/5778249928/job/15691793632?pr=1654#step:4:40).148:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '130.246.39.148',
  port: 443
}

12 links checked.

ERROR: 2 dead links found!
[✖] https://elettra.eu/ → Status: 0
[✖] https://pan-data.eu/sites/pan-data.eu/files/PaNdataODI-D6.1.pdf → Status: 0

=========================================================================
```

**Review by ElPaisano — CHANGES_REQUESTED** [review]
Once the links are fixed, we can get the PR in.

**Comment by twdragon** [comment]
@ElPaisano done, please, check again. One of the links is pure HTTP

**Review by ElPaisano — APPROVED** [review]
LGTM, thanks for fixing. Merging now

**Pull request merged**
